# Generated by Django 4.2.6 on 2024-05-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0094_orderitem_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
